---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-adapter
  name: hono-adapter-http-ingress
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hono-adapter
    deploymentconfig: hono-adapter-http-vertx
