kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /exports/influxdb-storage
    server: gprfc093.sbu.lab.eng.bos.redhat.com
