kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /exports/influxdb-storage   # NFS export name
    server: nfs-server.internal    # IP/hostname address of NFS server
readOnly: false
