{
 "title": "Test Metrics HTTP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Producers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http-publish",
     "select": [
      [
       { "params": [ "failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "sum_failure" ], "type": "alias" }
      ],
      [
       { "params": [ "sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "sum_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "sum_success" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http-publish",
     "select": [
      [
       { "params": [ "failureRatio" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "mean_failureRatio" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http-publish",
     "select": [
      [
       { "params": [ "sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http-publish",
     "select": [
      [
       { "params": [ "failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http-publish",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumer",
     "select": [
      [
       { "params": [ "messageCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "messageCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumer",
     "select": [
      [
       { "params": [ "messageCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Producer Errors / RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http-errors",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http-publish",
     "select": [
      [
       { "params": [ "avgDuration" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "durations" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}