---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enmasse
  name: messaging-nodeport
spec:
  type: NodePort
  ports:
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: 5671
      nodePort: 30671
  selector:
    capability: router
